version: '3'
services:
    entu:
        build:
            context: https://github.com/entu/entu.git
        container_name: entu
        command: python -u /usr/src/entu/app/main.py --logging=error
        restart: always
        environment:
            PORT: 80
            DEBUG: false
            AUTH_URL: https://auth.entu.ee/auth
            UPLOADS_PATH: /entu/uploads/
            FILES_PATH: /entu
            MYSQL_HOST:
            MYSQL_PORT:
            MYSQL_DATABASE:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MONGODB:
            CUSTOMERGROUP:
            INTERCOM_KEY:
        volumes:
            - /data/entu/files:/entu/files
            - /data/entu/thumbs:/entu/thumbs
            - /data/entu/uploads:/entu/uploads
            - /data/rds-combined-ca-bundle.pem:/entu/ssl/rds-combined-ca-bundle.pem:ro

    maintenance:
        build:
            context: https://github.com/entu/entu.git
        container_name: maintenance
        command: python -u /usr/src/entu/app/maintenance.py
        restart: always
        environment:
            MYSQL_HOST:
            MYSQL_PORT:
            MYSQL_DATABASE:
            MYSQL_USER:
            MYSQL_PASSWORD:
            CUSTOMERGROUP:
            VERBOSE: 1
        volumes:
            - /data/rds-combined-ca-bundle.pem:/entu/ssl/rds-combined-ca-bundle.pem:ro

    nginx:
        image: 'nginx:1.14'
        container_name: nginx
        restart: always
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - /data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - /data/nginx/ssl/dhparams.pem:/etc/nginx/dhparams.pem:ro
            - /data/nginx/ssl/id.crt:/etc/nginx/id.crt:ro
            - /data/nginx/sites:/etc/nginx/conf.d:ro
            - /data/nginx/log:/var/log/nginx
            - /data/letsencrypt/certs/archive:/etc/nginx/letsencrypt/archive:ro
            - /data/letsencrypt/certs/live:/etc/nginx/letsencrypt/live:ro
            - /data/letsencrypt/static:/etc/nginx/letsencrypt/static:ro
            - /data/entu/uploads:/entu/uploads
        depends_on:
            - entu
